
-- Table: PACKAGES
CREATE TABLE PACKAGES ( 
    NAME  TEXT    PRIMARY KEY,
    COUNT INTEGER DEFAULT 0 
);


-- Table: ABILITIES
CREATE TABLE ABILITIES ( 
    NAME        TEXT    PRIMARY KEY,
    DESCRIPTION TEXT,
    IS_MONARCH  INTEGER DEFAULT 0,
    IS_PASSIVE  INTEGER DEFAULT 0,
    IS_ONE_TIME INTEGER DEFAULT 0 
);


-- Table: FACTIONS
CREATE TABLE FACTIONS ( 
    NAME  TEXT    PRIMARY KEY,
    COUNT INTEGER DEFAULT 0 
);


-- Table: GENDERS
CREATE TABLE GENDERS ( 
    NAME  TEXT    PRIMARY KEY,
    COUNT INTEGER DEFAULT 0 
);


-- Table: HEROES_ROLE
CREATE TABLE HEROES_ROLE ( 
    NAME                          TEXT,
    TITLE                         TEXT,
    ID                            TEXT,
    PACKAGE                       TEXT,
    MAX_LIFE_POINTS               INTEGER DEFAULT 3,
    IS_MONARCH                    INTEGER DEFAULT 0,
    IS_DIVINE                     INTEGER DEFAULT 0,
    GENDER                        TEXT    DEFAULT 'MALE',
    FACTION                       TEXT,
    ABILITY1                      TEXT,
    ABILITY2                      TEXT,
    ABILITY3                      TEXT,
    ABILITY4                      TEXT,
    ABILITY5                      TEXT,
    ADDITIONAL_INFO_FOR_ABILITIES TEXT,
    HEAD_PORTRAIT                 BLOB,
    FULL_PORTRAIT                 BLOB,
    PRIMARY KEY ( NAME, TITLE, ID ASC ),
    FOREIGN KEY ( GENDER ) REFERENCES GENDERS ( NAME ),
    FOREIGN KEY ( FACTION ) REFERENCES FACTIONS ( NAME ),
    FOREIGN KEY ( ABILITY1 ) REFERENCES ABILITIES ( NAME ),
    FOREIGN KEY ( ABILITY2 ) REFERENCES ABILITIES ( NAME ),
    FOREIGN KEY ( ABILITY3 ) REFERENCES ABILITIES ( NAME ),
    FOREIGN KEY ( ABILITY4 ) REFERENCES ABILITIES ( NAME ),
    FOREIGN KEY ( ABILITY5 ) REFERENCES ABILITIES ( NAME ),
    FOREIGN KEY ( PACKAGE ) REFERENCES PACKAGES ( NAME ) 
);


-- Table: FAQ_ROLE
CREATE TABLE FAQ_ROLE ( 
    ID       INTEGER PRIMARY KEY AUTOINCREMENT,
    QUESTION TEXT,
    ANSWER   TEXT,
    HERO_ID  TEXT,
    FOREIGN KEY ( HERO_ID ) REFERENCES HEROES_ROLE ( ID ) 
);


-- Table: CARD_TYPE
CREATE TABLE CARD_TYPE ( 
    NAME  TEXT,
    VALUE INTEGER,
    COUNT INTEGER 
);


-- Table: FAQ_CARD_ROLE
CREATE TABLE FAQ_CARD_ROLE ( 
    ID        INTEGER PRIMARY KEY AUTOINCREMENT,
    QUESTION  TEXT,
    ANSWER    TEXT,
    CARD_NAME TEXT    REFERENCES CARD_ROLE ( NAME ) 
);


-- Table: CARDS_ROLE
CREATE TABLE CARDS_ROLE ( 
    NAME               TEXT    PRIMARY KEY,
    TIMING             TEXT,
    TARGET             TEXT,
    EFFECT             TEXT,
    SUPPLEMENTARY_INFO TEXT,
    PACKAGE            TEXT    REFERENCES PACKAGES ( NAME ),
    TYPE               INTEGER REFERENCES CARD_TYPE ( VALUE ),
    COUNT              INTEGER DEFAULT 1
);


-- Table: DECK_ROLE
CREATE TABLE DECK_ROLE ( 
    NAME    TEXT    REFERENCES CARDS_ROLE ( NAME ),
    SUIT    TEXT,
    RANK    TEXT,
    ID      INTEGER PRIMARY KEY AUTOINCREMENT,
    PACKAGE TEXT    REFERENCES PACKAGES ( NAME ) 
);


-- Table: GENERAL_RULE
CREATE TABLE GENERAL_RULE ( 
    SECTION  INTEGER PRIMARY KEY ASC,
    HEADER   TEXT,
    CONTENTS TEXT 
);


-- Table: TERMINOLOGIES
CREATE TABLE TERMINOLOGIES ( 
    SECTION  INTEGER PRIMARY KEY,
    HEADER   TEXT,
    CONTENTS TEXT 
);

